//
//  UICatalog.swift
//  AISDK
//
//  Component catalog for generative UI with json-render pattern
//  Defines available UI components for LLM prompt generation
//

import Foundation

// MARK: - UIComponentDefinition Protocol

/// Protocol defining a UI component that can be generated by LLM
///
/// Each component definition describes:
/// - The component type name (used in JSON)
/// - Human-readable description for the LLM
/// - Whether it can contain child components
/// - Schema description for the props
/// - Validation logic for incoming props
public protocol UIComponentDefinition: Sendable {
    /// The props type for this component
    associatedtype Props: Codable & Sendable

    /// The type identifier used in JSON (e.g., "Text", "Button")
    static var type: String { get }

    /// Human-readable description for the LLM prompt
    static var description: String { get }

    /// Whether this component can contain children
    static var hasChildren: Bool { get }

    /// Human-readable description of the props schema for LLM
    static var propsSchemaDescription: String { get }

    /// Allowed prop keys for strict validation (empty = allow all)
    static var allowedPropKeys: Set<String> { get }

    /// Validate decoded props, throwing on invalid values
    ///
    /// - Parameter props: The decoded props to validate
    /// - Throws: `UIComponentValidationError` if validation fails
    static func validate(props: Props) throws

    /// Catalog-aware validation for props that reference actions/validators
    ///
    /// - Parameters:
    ///   - props: The decoded props to validate
    ///   - actions: Registered action names in the catalog
    ///   - validators: Registered validator names in the catalog
    /// - Throws: `UIComponentValidationError` if validation fails
    static func validateWithCatalog(
        props: Props,
        actions: Set<String>,
        validators: Set<String>
    ) throws
}

// MARK: - Default Implementation

extension UIComponentDefinition {
    /// Default validation - no-op (override for custom validation)
    public static func validate(props: Props) throws {
        // Default implementation does nothing
    }

    /// Default catalog-aware validation - delegates to regular validation
    public static func validateWithCatalog(
        props: Props,
        actions: Set<String>,
        validators: Set<String>
    ) throws {
        // Default implementation just calls regular validation
        try validate(props: props)
    }

    /// Default allowed prop keys - empty means no strict validation
    public static var allowedPropKeys: Set<String> {
        []
    }
}

// MARK: - UIActionDefinition

/// Definition of an action that can be triggered by UI components
public struct UIActionDefinition: Sendable {
    /// The action identifier
    public let name: String

    /// Human-readable description
    public let description: String

    /// Parameter schema description
    public let parametersDescription: String?

    public init(
        name: String,
        description: String,
        parametersDescription: String? = nil
    ) {
        self.name = name
        self.description = description
        self.parametersDescription = parametersDescription
    }
}

// MARK: - UIValidatorDefinition

/// Definition of a validator that can be used on input components
public struct UIValidatorDefinition: Sendable {
    /// The validator identifier
    public let name: String

    /// Human-readable description
    public let description: String

    /// Parameter schema description
    public let parametersDescription: String?

    public init(
        name: String,
        description: String,
        parametersDescription: String? = nil
    ) {
        self.name = name
        self.description = description
        self.parametersDescription = parametersDescription
    }
}

// MARK: - UIComponentValidationError

/// Errors that can occur during component validation
public enum UIComponentValidationError: Error, Sendable {
    /// A required prop is missing during decoding
    case missingRequiredProp(component: String, prop: String)

    /// A prop value is invalid
    case invalidPropValue(component: String, prop: String, reason: String)

    /// Component type is not registered
    case unknownComponentType(String)

    /// General validation failure (includes decoding failures)
    case validationFailed(component: String, reason: String)

    /// Props data failed to decode
    case decodingFailed(component: String, reason: String)

    /// Unknown prop key in JSON (strict mode)
    case unknownProp(component: String, prop: String)

    /// Action name not registered in catalog
    case unknownAction(component: String, action: String)

    /// Validator name not registered in catalog
    case unknownValidator(component: String, validator: String)

    /// Component type name is invalid (empty or whitespace)
    case invalidComponentTypeName(String)

    /// Duplicate component type registration attempted
    case duplicateComponentType(String)
}

extension UIComponentValidationError: LocalizedError {
    public var errorDescription: String? {
        switch self {
        case .missingRequiredProp(let component, let prop):
            return "Component '\(component)' missing required prop '\(prop)'"
        case .invalidPropValue(let component, let prop, let reason):
            return "Component '\(component)' has invalid value for prop '\(prop)': \(reason)"
        case .unknownComponentType(let type):
            return "Unknown component type: \(type)"
        case .validationFailed(let component, let reason):
            return "Component '\(component)' validation failed: \(reason)"
        case .decodingFailed(let component, let reason):
            return "Component '\(component)' props decoding failed: \(reason)"
        case .unknownProp(let component, let prop):
            return "Component '\(component)' has unknown prop '\(prop)'"
        case .unknownAction(let component, let action):
            return "Component '\(component)' references unknown action '\(action)'"
        case .unknownValidator(let component, let validator):
            return "Component '\(component)' references unknown validator '\(validator)'"
        case .invalidComponentTypeName(let name):
            return "Invalid component type name: '\(name)' (must be non-empty)"
        case .duplicateComponentType(let type):
            return "Duplicate component type registration: '\(type)'"
        }
    }
}

// MARK: - AnyUIComponentDefinition

/// Type-erased wrapper for UIComponentDefinition
///
/// Enables storing heterogeneous component definitions in collections.
public struct AnyUIComponentDefinition: Sendable {
    /// The component type identifier
    public let type: String

    /// Human-readable description
    public let description: String

    /// Whether this component supports children
    public let hasChildren: Bool

    /// Props schema description for LLM
    public let propsSchemaDescription: String

    /// Allowed prop keys for strict validation
    public let allowedPropKeys: Set<String>

    /// Type-erased validation function that always throws UIComponentValidationError
    private let _validateWithCatalog: @Sendable (Data, Set<String>, Set<String>) throws -> Void

    /// Creates a type-erased wrapper for a component definition
    ///
    /// - Parameter definitionType: The concrete UIComponentDefinition type
    public init<T: UIComponentDefinition>(_ definitionType: T.Type) {
        self.type = T.type
        self.description = T.description
        self.hasChildren = T.hasChildren
        self.propsSchemaDescription = T.propsSchemaDescription
        self.allowedPropKeys = T.allowedPropKeys

        let componentType = T.type  // Capture for closure
        let allowedKeys = T.allowedPropKeys

        self._validateWithCatalog = { data, actions, validators in
            // First, check for unknown keys if strict validation is enabled
            if !allowedKeys.isEmpty {
                try Self.validateUnknownKeys(
                    data: data,
                    allowedKeys: allowedKeys,
                    componentType: componentType
                )
            }

            // Decode props with error wrapping
            let decoder = JSONDecoder()
            decoder.keyDecodingStrategy = .convertFromSnakeCase

            let props: T.Props
            do {
                props = try decoder.decode(T.Props.self, from: data)
            } catch let decodingError as DecodingError {
                // Extract meaningful error message from DecodingError
                let reason: String
                switch decodingError {
                case .keyNotFound(let key, _):
                    throw UIComponentValidationError.missingRequiredProp(
                        component: componentType,
                        prop: key.stringValue
                    )
                case .typeMismatch(let expectedType, let context):
                    reason = "Expected \(expectedType) at \(context.codingPath.map(\.stringValue).joined(separator: "."))"
                case .valueNotFound(let expectedType, let context):
                    reason = "Missing value of type \(expectedType) at \(context.codingPath.map(\.stringValue).joined(separator: "."))"
                case .dataCorrupted(let context):
                    reason = context.debugDescription
                @unknown default:
                    reason = decodingError.localizedDescription
                }
                throw UIComponentValidationError.decodingFailed(
                    component: componentType,
                    reason: reason
                )
            } catch {
                throw UIComponentValidationError.decodingFailed(
                    component: componentType,
                    reason: error.localizedDescription
                )
            }

            // Run catalog-aware validation
            do {
                try T.validateWithCatalog(props: props, actions: actions, validators: validators)
            } catch let validationError as UIComponentValidationError {
                throw validationError
            } catch {
                throw UIComponentValidationError.validationFailed(
                    component: componentType,
                    reason: error.localizedDescription
                )
            }
        }
    }

    /// Check for unknown keys in JSON data
    private static func validateUnknownKeys(
        data: Data,
        allowedKeys: Set<String>,
        componentType: String
    ) throws {
        // Parse JSON to get all keys
        guard let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return  // Let decoder handle malformed JSON
        }

        // Convert snake_case keys to camelCase for comparison
        let jsonKeys = Set(json.keys.map { key -> String in
            // Convert snake_case to camelCase
            let parts = key.split(separator: "_")
            if parts.count <= 1 { return key }
            return parts.enumerated().map { index, part in
                index == 0 ? String(part) : String(part).capitalized
            }.joined()
        })

        // Find unknown keys
        for key in jsonKeys {
            if !allowedKeys.contains(key) {
                throw UIComponentValidationError.unknownProp(
                    component: componentType,
                    prop: key
                )
            }
        }
    }

    /// Validate props data for this component (without catalog context)
    ///
    /// - Parameter propsData: JSON data for the props
    /// - Throws: `UIComponentValidationError` for any validation or decoding failure
    public func validate(propsData: Data) throws {
        // Validate without catalog context (empty action/validator sets)
        try _validateWithCatalog(propsData, [], [])
    }

    /// Validate props data with catalog context for action/validator validation
    ///
    /// - Parameters:
    ///   - propsData: JSON data for the props
    ///   - actions: Registered action names in the catalog
    ///   - validators: Registered validator names in the catalog
    /// - Throws: `UIComponentValidationError` for any validation or decoding failure
    public func validateWithCatalog(
        propsData: Data,
        actions: Set<String>,
        validators: Set<String>
    ) throws {
        try _validateWithCatalog(propsData, actions, validators)
    }
}

// MARK: - UICatalog

/// Component catalog defining available UI components for LLM
///
/// `UICatalog` is the central registry for generative UI components. It provides:
/// - Component definitions with props schemas
/// - Action definitions for interactive elements
/// - Validator definitions for input validation
/// - System prompt generation for LLM context
///
/// ## Usage
/// ```swift
/// // Use the default Core 8 catalog
/// let catalog = UICatalog.core8
///
/// // Generate system prompt for LLM
/// let prompt = catalog.generatePrompt()
/// ```
///
/// ## Custom Catalog
/// ```swift
/// var catalog = UICatalog()
/// catalog.register(MyCustomComponent.self)
/// catalog.registerAction(UIActionDefinition(name: "submit", description: "Submit form"))
/// ```
public struct UICatalog: Sendable {
    /// Registered component definitions by type name
    public private(set) var components: [String: AnyUIComponentDefinition]

    /// Registered action definitions by name
    public private(set) var actions: [String: UIActionDefinition]

    /// Registered validator definitions by name
    public private(set) var validators: [String: UIValidatorDefinition]

    /// Creates an empty catalog
    public init() {
        self.components = [:]
        self.actions = [:]
        self.validators = [:]
    }

    /// Creates a catalog with predefined components (internal, unchecked)
    ///
    /// - Parameter componentTypes: Array of component definition types to register
    /// - Note: Uses unchecked registration - assumes valid, non-duplicate types.
    ///         For public use, create an empty catalog and use `register` method.
    init<each T: UIComponentDefinition>(componentTypes: repeat (each T).Type) {
        self.components = [:]
        self.actions = [:]
        self.validators = [:]
        repeat registerUnchecked((each componentTypes))
    }

    // MARK: - Registration

    /// Register a component definition
    ///
    /// - Parameter definitionType: The component definition type to register
    /// - Throws: `UIComponentValidationError.invalidComponentTypeName` if type name is empty/whitespace,
    ///           `UIComponentValidationError.duplicateComponentType` if type is already registered
    public mutating func register<T: UIComponentDefinition>(_ definitionType: T.Type) throws {
        let typeName = T.type.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !typeName.isEmpty else {
            throw UIComponentValidationError.invalidComponentTypeName(T.type)
        }
        // Reject types with leading/trailing whitespace to ensure consistency
        guard T.type == typeName else {
            throw UIComponentValidationError.invalidComponentTypeName(T.type)
        }
        guard components[typeName] == nil else {
            throw UIComponentValidationError.duplicateComponentType(typeName)
        }
        let wrapped = AnyUIComponentDefinition(definitionType)
        components[typeName] = wrapped
    }

    /// Register a component definition (internal, non-throwing for core8 initialization)
    ///
    /// - Parameter definitionType: The component definition type to register
    /// - Note: This method is internal and used for core8 catalog initialization
    mutating func registerUnchecked<T: UIComponentDefinition>(_ definitionType: T.Type) {
        let wrapped = AnyUIComponentDefinition(definitionType)
        components[T.type] = wrapped
    }

    /// Register an action definition
    ///
    /// - Parameter action: The action definition to register
    public mutating func registerAction(_ action: UIActionDefinition) {
        actions[action.name] = action
    }

    /// Register a validator definition
    ///
    /// - Parameter validator: The validator definition to register
    public mutating func registerValidator(_ validator: UIValidatorDefinition) {
        validators[validator.name] = validator
    }

    // MARK: - Lookup

    /// Get a component definition by type name
    ///
    /// - Parameter type: The component type identifier
    /// - Returns: The component definition, or nil if not found
    public func component(forType type: String) -> AnyUIComponentDefinition? {
        components[type]
    }

    /// Check if a component type is registered
    ///
    /// - Parameter type: The component type identifier
    /// - Returns: True if the component is registered
    public func hasComponent(_ type: String) -> Bool {
        components[type] != nil
    }

    /// Get all registered component type names (sorted)
    public var registeredComponentTypes: [String] {
        components.keys.sorted()
    }

    // MARK: - Validation

    /// Validate a component type and its props
    ///
    /// - Parameters:
    ///   - type: The component type identifier
    ///   - propsData: JSON data for the props
    /// - Throws: `UIComponentValidationError` if validation fails (including decoding errors,
    ///           unknown props, unknown actions/validators)
    public func validate(type: String, propsData: Data) throws {
        guard let definition = components[type] else {
            throw UIComponentValidationError.unknownComponentType(type)
        }
        // Use catalog-aware validation to check action/validator references
        try definition.validateWithCatalog(
            propsData: propsData,
            actions: Set(actions.keys),
            validators: Set(validators.keys)
        )
    }

    // MARK: - Prompt Generation

    /// Generate a system prompt describing available components for LLM
    ///
    /// This prompt can be included in the system message to inform the LLM
    /// about available UI components and the expected output format.
    ///
    /// - Returns: A formatted prompt string
    public func generatePrompt() -> String {
        var prompt = "You can generate UI using these components:\n\n"

        // Sort by type name for deterministic output
        let sortedComponents = components.sorted { $0.key < $1.key }

        for (_, definition) in sortedComponents {
            prompt += "## \(definition.type)\n"
            prompt += "Description: \(definition.description)\n"
            prompt += "Props: \(definition.propsSchemaDescription)\n"
            if definition.hasChildren {
                prompt += "Can contain children: Yes\n"
            } else {
                prompt += "Can contain children: No\n"
            }
            prompt += "\n"
        }

        // Add actions section if any registered
        if !actions.isEmpty {
            prompt += "## Available Actions\n\n"
            let sortedActions = actions.sorted { $0.key < $1.key }
            for (_, action) in sortedActions {
                prompt += "- **\(action.name)**: \(action.description)"
                if let params = action.parametersDescription {
                    prompt += " (Parameters: \(params))"
                }
                prompt += "\n"
            }
            prompt += "\n"
        }

        // Add validators section if any registered
        if !validators.isEmpty {
            prompt += "## Available Validators\n\n"
            let sortedValidators = validators.sorted { $0.key < $1.key }
            for (_, validator) in sortedValidators {
                prompt += "- **\(validator.name)**: \(validator.description)"
                if let params = validator.parametersDescription {
                    prompt += " (Parameters: \(params))"
                }
                prompt += "\n"
            }
            prompt += "\n"
        }

        // Add output format specification (json-render pattern)
        prompt += """

        Output format: JSON with structure:
        {
          "root": "<key of root element>",
          "elements": {
            "<key>": {
              "type": "<component type>",
              "props": { ... },
              "children": ["<child key>", ...]
            }
          }
        }

        Rules:
        - Each element must have a unique key
        - The "root" field must reference an existing element key
        - Child keys must reference existing element keys
        - Only components marked "Can contain children: Yes" may have a "children" array
        - Components marked "Can contain children: No" must omit the "children" field
        - Use only registered component types listed above
        """

        return prompt
    }
}

// MARK: - Core 8 Placeholder Definitions (Internal)

// Note: Full component definitions are implemented in Task 5.2
// These are internal placeholder definitions for the core8 catalog
// They will be replaced by public definitions in Task 5.2

/// Placeholder for Text component (full implementation in Task 5.2)
struct TextComponentDefinitionPlaceholder: UIComponentDefinition {
    struct Props: Codable, Sendable {
        let content: String
        let style: String?
        let accessibilityLabel: String?

        init(content: String, style: String? = nil, accessibilityLabel: String? = nil) {
            self.content = content
            self.style = style
            self.accessibilityLabel = accessibilityLabel
        }
    }

    static let type = "Text"
    static let description = "Display text content"
    static let hasChildren = false
    static let propsSchemaDescription = "{ content: string (required), style?: string, accessibilityLabel?: string }"
    static let allowedPropKeys: Set<String> = ["content", "style", "accessibilityLabel"]

    static func validate(props: Props) throws {
        if props.content.isEmpty {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "content",
                reason: "Content cannot be empty"
            )
        }
    }
}

/// Placeholder for Button component (full implementation in Task 5.2)
struct ButtonComponentDefinitionPlaceholder: UIComponentDefinition {
    struct Props: Codable, Sendable {
        let title: String
        let action: String
        let style: String?
        let disabled: Bool?
        let accessibilityLabel: String?
        let accessibilityHint: String?
        let accessibilityTraits: [String]?

        init(
            title: String,
            action: String,
            style: String? = nil,
            disabled: Bool? = nil,
            accessibilityLabel: String? = nil,
            accessibilityHint: String? = nil,
            accessibilityTraits: [String]? = nil
        ) {
            self.title = title
            self.action = action
            self.style = style
            self.disabled = disabled
            self.accessibilityLabel = accessibilityLabel
            self.accessibilityHint = accessibilityHint
            self.accessibilityTraits = accessibilityTraits
        }
    }

    static let type = "Button"
    static let description = "Interactive button that triggers an action"
    static let hasChildren = false
    static let propsSchemaDescription = """
        { title: string (required), action: string (required), style?: string, disabled?: boolean, \
        accessibilityLabel?: string, accessibilityHint?: string, accessibilityTraits?: string[] }
        """
    static let allowedPropKeys: Set<String> = [
        "title", "action", "style", "disabled",
        "accessibilityLabel", "accessibilityHint", "accessibilityTraits"
    ]

    static func validate(props: Props) throws {
        if props.title.isEmpty {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "title",
                reason: "Title cannot be empty"
            )
        }
        if props.action.isEmpty {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "action",
                reason: "Action cannot be empty"
            )
        }
    }

    static func validateWithCatalog(
        props: Props,
        actions: Set<String>,
        validators: Set<String>
    ) throws {
        // Basic validation
        try validate(props: props)

        // Catalog-aware validation: check action exists in registered actions
        if !actions.contains(props.action) {
            throw UIComponentValidationError.unknownAction(
                component: type,
                action: props.action
            )
        }
    }
}

/// Placeholder for Card component (full implementation in Task 5.2)
struct CardComponentDefinitionPlaceholder: UIComponentDefinition {
    struct Props: Codable, Sendable {
        let title: String?
        let subtitle: String?
        let style: String?

        init(title: String? = nil, subtitle: String? = nil, style: String? = nil) {
            self.title = title
            self.subtitle = subtitle
            self.style = style
        }
    }

    static let type = "Card"
    static let description = "Container card with optional title and subtitle"
    static let hasChildren = true
    static let propsSchemaDescription = "{ title?: string, subtitle?: string, style?: string }"
    static let allowedPropKeys: Set<String> = ["title", "subtitle", "style"]
}

/// Input type enum for validation
public enum InputType: String, Codable, Sendable {
    case text
    case email
    case password
    case number
}

/// Placeholder for Input component (full implementation in Task 5.2)
struct InputComponentDefinitionPlaceholder: UIComponentDefinition {
    struct Props: Codable, Sendable {
        let label: String
        let placeholder: String?
        let name: String
        let type: InputType?
        let required: Bool?
        let validation: String?

        init(
            label: String,
            name: String,
            placeholder: String? = nil,
            type: InputType? = nil,
            required: Bool? = nil,
            validation: String? = nil
        ) {
            self.label = label
            self.name = name
            self.placeholder = placeholder
            self.type = type
            self.required = required
            self.validation = validation
        }
    }

    static let type = "Input"
    static let description = "Text input field for user data entry"
    static let hasChildren = false
    static let propsSchemaDescription = """
        { label: string (required), name: string (required), placeholder?: string, \
        type?: 'text'|'email'|'password'|'number', required?: boolean, validation?: string }
        """
    static let allowedPropKeys: Set<String> = ["label", "placeholder", "name", "type", "required", "validation"]

    static func validate(props: Props) throws {
        if props.label.isEmpty {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "label",
                reason: "Label cannot be empty"
            )
        }
        if props.name.isEmpty {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "name",
                reason: "Name cannot be empty"
            )
        }
        // Note: type is now an enum, so invalid values will cause a decoding error
    }

    static func validateWithCatalog(
        props: Props,
        actions: Set<String>,
        validators: Set<String>
    ) throws {
        // Basic validation
        try validate(props: props)

        // Catalog-aware validation: check validator exists in registered validators
        if let validation = props.validation, !validation.isEmpty {
            if !validators.contains(validation) {
                throw UIComponentValidationError.unknownValidator(
                    component: type,
                    validator: validation
                )
            }
        }
    }
}

/// List style enum for validation
public enum ListStyle: String, Codable, Sendable {
    case ordered
    case unordered
    case plain
}

/// Placeholder for List component (full implementation in Task 5.2)
struct ListComponentDefinitionPlaceholder: UIComponentDefinition {
    struct Props: Codable, Sendable {
        let style: ListStyle?

        init(style: ListStyle? = nil) {
            self.style = style
        }
    }

    static let type = "List"
    static let description = "Ordered or unordered list container"
    static let hasChildren = true
    static let propsSchemaDescription = "{ style?: 'ordered'|'unordered'|'plain' }"
    static let allowedPropKeys: Set<String> = ["style"]
    // Note: style is now an enum, so invalid values will cause a decoding error
}

/// Placeholder for Image component (full implementation in Task 5.2)
struct ImageComponentDefinitionPlaceholder: UIComponentDefinition {
    struct Props: Codable, Sendable {
        let url: String
        let alt: String?
        let width: Double?
        let height: Double?

        init(url: String, alt: String? = nil, width: Double? = nil, height: Double? = nil) {
            self.url = url
            self.alt = alt
            self.width = width
            self.height = height
        }
    }

    static let type = "Image"
    static let description = "Display an image from URL"
    static let hasChildren = false
    static let propsSchemaDescription = "{ url: string (required), alt?: string, width?: number, height?: number }"
    static let allowedPropKeys: Set<String> = ["url", "alt", "width", "height"]

    static func validate(props: Props) throws {
        if props.url.isEmpty {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "url",
                reason: "URL cannot be empty"
            )
        }
        if let width = props.width, width <= 0 {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "width",
                reason: "Width must be positive"
            )
        }
        if let height = props.height, height <= 0 {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "height",
                reason: "Height must be positive"
            )
        }
    }
}

/// Stack direction enum for validation
public enum StackDirection: String, Codable, Sendable {
    case horizontal
    case vertical
}

/// Stack alignment enum for validation
public enum StackAlignment: String, Codable, Sendable {
    case leading
    case center
    case trailing
}

/// Placeholder for Stack component (full implementation in Task 5.2)
struct StackComponentDefinitionPlaceholder: UIComponentDefinition {
    struct Props: Codable, Sendable {
        let direction: StackDirection
        let spacing: Double?
        let alignment: StackAlignment?

        init(direction: StackDirection = .vertical, spacing: Double? = nil, alignment: StackAlignment? = nil) {
            self.direction = direction
            self.spacing = spacing
            self.alignment = alignment
        }
    }

    static let type = "Stack"
    static let description = "Layout container for horizontal or vertical arrangement"
    static let hasChildren = true
    static let propsSchemaDescription = """
        { direction: 'horizontal'|'vertical' (required), spacing?: number, alignment?: 'leading'|'center'|'trailing' }
        """
    static let allowedPropKeys: Set<String> = ["direction", "spacing", "alignment"]

    static func validate(props: Props) throws {
        // Direction and alignment are now enums, so invalid values cause decoding errors
        if let spacing = props.spacing, spacing < 0 {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "spacing",
                reason: "Spacing cannot be negative"
            )
        }
    }
}

/// Placeholder for Spacer component (full implementation in Task 5.2)
struct SpacerComponentDefinitionPlaceholder: UIComponentDefinition {
    struct Props: Codable, Sendable {
        let size: Double?

        init(size: Double? = nil) {
            self.size = size
        }
    }

    static let type = "Spacer"
    static let description = "Flexible space between elements"
    static let hasChildren = false
    static let propsSchemaDescription = "{ size?: number }"
    static let allowedPropKeys: Set<String> = ["size"]

    static func validate(props: Props) throws {
        if let size = props.size, size < 0 {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "size",
                reason: "Size cannot be negative"
            )
        }
    }
}

// MARK: - Core 8 Catalog

extension UICatalog {
    /// Default catalog with Core 8 components
    ///
    /// The Core 8 components are:
    /// - **Text**: Display text content
    /// - **Button**: Interactive button
    /// - **Card**: Container with title/subtitle
    /// - **Input**: Text input field
    /// - **List**: Ordered/unordered list
    /// - **Image**: Image display
    /// - **Stack**: Layout container (horizontal/vertical)
    /// - **Spacer**: Flexible space
    public static let core8: UICatalog = {
        var catalog = UICatalog()

        // Register Core 8 components (public definitions from Core8Components.swift)
        catalog.registerUnchecked(TextComponentDefinition.self)
        catalog.registerUnchecked(ButtonComponentDefinition.self)
        catalog.registerUnchecked(CardComponentDefinition.self)
        catalog.registerUnchecked(InputComponentDefinition.self)
        catalog.registerUnchecked(ListComponentDefinition.self)
        catalog.registerUnchecked(ImageComponentDefinition.self)
        catalog.registerUnchecked(StackComponentDefinition.self)
        catalog.registerUnchecked(SpacerComponentDefinition.self)

        // Register common actions
        catalog.registerAction(UIActionDefinition(
            name: "submit",
            description: "Submit a form",
            parametersDescription: "{ formId?: string }"
        ))
        catalog.registerAction(UIActionDefinition(
            name: "navigate",
            description: "Navigate to a destination",
            parametersDescription: "{ destination: string }"
        ))
        catalog.registerAction(UIActionDefinition(
            name: "dismiss",
            description: "Dismiss the current UI"
        ))

        // Register common validators
        catalog.registerValidator(UIValidatorDefinition(
            name: "required",
            description: "Field must have a value"
        ))
        catalog.registerValidator(UIValidatorDefinition(
            name: "email",
            description: "Field must be a valid email address"
        ))
        catalog.registerValidator(UIValidatorDefinition(
            name: "minLength",
            description: "Field must have minimum length",
            parametersDescription: "{ length: number }"
        ))
        catalog.registerValidator(UIValidatorDefinition(
            name: "maxLength",
            description: "Field must not exceed maximum length",
            parametersDescription: "{ length: number }"
        ))
        catalog.registerValidator(UIValidatorDefinition(
            name: "pattern",
            description: "Field must match regex pattern",
            parametersDescription: "{ pattern: string }"
        ))

        return catalog
    }()
}
