//
//  UICatalog.swift
//  AISDK
//
//  Component catalog for generative UI with json-render pattern
//  Defines available UI components for LLM prompt generation
//

import Foundation

// MARK: - UIComponentDefinition Protocol

/// Protocol defining a UI component that can be generated by LLM
///
/// Each component definition describes:
/// - The component type name (used in JSON)
/// - Human-readable description for the LLM
/// - Whether it can contain child components
/// - Schema description for the props
/// - Validation logic for incoming props
public protocol UIComponentDefinition: Sendable {
    /// The props type for this component
    associatedtype Props: Codable & Sendable

    /// The type identifier used in JSON (e.g., "Text", "Button")
    static var type: String { get }

    /// Human-readable description for the LLM prompt
    static var description: String { get }

    /// Whether this component can contain children
    static var hasChildren: Bool { get }

    /// Human-readable description of the props schema for LLM
    static var propsSchemaDescription: String { get }

    /// Validate decoded props, throwing on invalid values
    ///
    /// - Parameter props: The decoded props to validate
    /// - Throws: `UIComponentValidationError` if validation fails
    static func validate(props: Props) throws
}

// MARK: - Default Implementation

extension UIComponentDefinition {
    /// Default validation - no-op (override for custom validation)
    public static func validate(props: Props) throws {
        // Default implementation does nothing
    }
}

// MARK: - UIActionDefinition

/// Definition of an action that can be triggered by UI components
public struct UIActionDefinition: Sendable {
    /// The action identifier
    public let name: String

    /// Human-readable description
    public let description: String

    /// Parameter schema description
    public let parametersDescription: String?

    public init(
        name: String,
        description: String,
        parametersDescription: String? = nil
    ) {
        self.name = name
        self.description = description
        self.parametersDescription = parametersDescription
    }
}

// MARK: - UIValidatorDefinition

/// Definition of a validator that can be used on input components
public struct UIValidatorDefinition: Sendable {
    /// The validator identifier
    public let name: String

    /// Human-readable description
    public let description: String

    /// Parameter schema description
    public let parametersDescription: String?

    public init(
        name: String,
        description: String,
        parametersDescription: String? = nil
    ) {
        self.name = name
        self.description = description
        self.parametersDescription = parametersDescription
    }
}

// MARK: - UIComponentValidationError

/// Errors that can occur during component validation
public enum UIComponentValidationError: Error, Sendable {
    /// A required prop is missing
    case missingRequiredProp(component: String, prop: String)

    /// A prop value is invalid
    case invalidPropValue(component: String, prop: String, reason: String)

    /// Component type is not registered
    case unknownComponentType(String)

    /// General validation failure
    case validationFailed(component: String, reason: String)
}

extension UIComponentValidationError: LocalizedError {
    public var errorDescription: String? {
        switch self {
        case .missingRequiredProp(let component, let prop):
            return "Component '\(component)' missing required prop '\(prop)'"
        case .invalidPropValue(let component, let prop, let reason):
            return "Component '\(component)' has invalid value for prop '\(prop)': \(reason)"
        case .unknownComponentType(let type):
            return "Unknown component type: \(type)"
        case .validationFailed(let component, let reason):
            return "Component '\(component)' validation failed: \(reason)"
        }
    }
}

// MARK: - AnyUIComponentDefinition

/// Type-erased wrapper for UIComponentDefinition
///
/// Enables storing heterogeneous component definitions in collections.
public struct AnyUIComponentDefinition: Sendable {
    /// The component type identifier
    public let type: String

    /// Human-readable description
    public let description: String

    /// Whether this component supports children
    public let hasChildren: Bool

    /// Props schema description for LLM
    public let propsSchemaDescription: String

    /// Type-erased validation function
    private let _validate: @Sendable (Data) throws -> Void

    /// Creates a type-erased wrapper for a component definition
    ///
    /// - Parameter definitionType: The concrete UIComponentDefinition type
    public init<T: UIComponentDefinition>(_ definitionType: T.Type) {
        self.type = T.type
        self.description = T.description
        self.hasChildren = T.hasChildren
        self.propsSchemaDescription = T.propsSchemaDescription

        self._validate = { data in
            let decoder = JSONDecoder()
            decoder.keyDecodingStrategy = .convertFromSnakeCase
            let props = try decoder.decode(T.Props.self, from: data)
            try T.validate(props: props)
        }
    }

    /// Validate props data for this component
    ///
    /// - Parameter propsData: JSON data for the props
    /// - Throws: Decoding or validation errors
    public func validate(propsData: Data) throws {
        try _validate(propsData)
    }
}

// MARK: - UICatalog

/// Component catalog defining available UI components for LLM
///
/// `UICatalog` is the central registry for generative UI components. It provides:
/// - Component definitions with props schemas
/// - Action definitions for interactive elements
/// - Validator definitions for input validation
/// - System prompt generation for LLM context
///
/// ## Usage
/// ```swift
/// // Use the default Core 8 catalog
/// let catalog = UICatalog.core8
///
/// // Generate system prompt for LLM
/// let prompt = catalog.generatePrompt()
/// ```
///
/// ## Custom Catalog
/// ```swift
/// var catalog = UICatalog()
/// catalog.register(MyCustomComponent.self)
/// catalog.registerAction(UIActionDefinition(name: "submit", description: "Submit form"))
/// ```
public struct UICatalog: Sendable {
    /// Registered component definitions by type name
    public private(set) var components: [String: AnyUIComponentDefinition]

    /// Registered action definitions by name
    public private(set) var actions: [String: UIActionDefinition]

    /// Registered validator definitions by name
    public private(set) var validators: [String: UIValidatorDefinition]

    /// Creates an empty catalog
    public init() {
        self.components = [:]
        self.actions = [:]
        self.validators = [:]
    }

    /// Creates a catalog with predefined components
    ///
    /// - Parameter componentTypes: Array of component definition types to register
    public init<each T: UIComponentDefinition>(componentTypes: repeat (each T).Type) {
        self.components = [:]
        self.actions = [:]
        self.validators = [:]
        repeat register((each componentTypes))
    }

    // MARK: - Registration

    /// Register a component definition
    ///
    /// - Parameter definitionType: The component definition type to register
    public mutating func register<T: UIComponentDefinition>(_ definitionType: T.Type) {
        let wrapped = AnyUIComponentDefinition(definitionType)
        components[T.type] = wrapped
    }

    /// Register an action definition
    ///
    /// - Parameter action: The action definition to register
    public mutating func registerAction(_ action: UIActionDefinition) {
        actions[action.name] = action
    }

    /// Register a validator definition
    ///
    /// - Parameter validator: The validator definition to register
    public mutating func registerValidator(_ validator: UIValidatorDefinition) {
        validators[validator.name] = validator
    }

    // MARK: - Lookup

    /// Get a component definition by type name
    ///
    /// - Parameter type: The component type identifier
    /// - Returns: The component definition, or nil if not found
    public func component(forType type: String) -> AnyUIComponentDefinition? {
        components[type]
    }

    /// Check if a component type is registered
    ///
    /// - Parameter type: The component type identifier
    /// - Returns: True if the component is registered
    public func hasComponent(_ type: String) -> Bool {
        components[type] != nil
    }

    /// Get all registered component type names (sorted)
    public var registeredComponentTypes: [String] {
        components.keys.sorted()
    }

    // MARK: - Validation

    /// Validate a component type and its props
    ///
    /// - Parameters:
    ///   - type: The component type identifier
    ///   - propsData: JSON data for the props
    /// - Throws: `UIComponentValidationError` if validation fails
    public func validate(type: String, propsData: Data) throws {
        guard let definition = components[type] else {
            throw UIComponentValidationError.unknownComponentType(type)
        }
        try definition.validate(propsData: propsData)
    }

    // MARK: - Prompt Generation

    /// Generate a system prompt describing available components for LLM
    ///
    /// This prompt can be included in the system message to inform the LLM
    /// about available UI components and the expected output format.
    ///
    /// - Returns: A formatted prompt string
    public func generatePrompt() -> String {
        var prompt = "You can generate UI using these components:\n\n"

        // Sort by type name for deterministic output
        let sortedComponents = components.sorted { $0.key < $1.key }

        for (_, definition) in sortedComponents {
            prompt += "## \(definition.type)\n"
            prompt += "Description: \(definition.description)\n"
            prompt += "Props: \(definition.propsSchemaDescription)\n"
            if definition.hasChildren {
                prompt += "Can contain children: Yes\n"
            }
            prompt += "\n"
        }

        // Add actions section if any registered
        if !actions.isEmpty {
            prompt += "## Available Actions\n\n"
            let sortedActions = actions.sorted { $0.key < $1.key }
            for (_, action) in sortedActions {
                prompt += "- **\(action.name)**: \(action.description)"
                if let params = action.parametersDescription {
                    prompt += " (Parameters: \(params))"
                }
                prompt += "\n"
            }
            prompt += "\n"
        }

        // Add validators section if any registered
        if !validators.isEmpty {
            prompt += "## Available Validators\n\n"
            let sortedValidators = validators.sorted { $0.key < $1.key }
            for (_, validator) in sortedValidators {
                prompt += "- **\(validator.name)**: \(validator.description)"
                if let params = validator.parametersDescription {
                    prompt += " (Parameters: \(params))"
                }
                prompt += "\n"
            }
            prompt += "\n"
        }

        // Add output format specification (json-render pattern)
        prompt += """

        Output format: JSON with structure:
        {
          "root": "<key of root element>",
          "elements": {
            "<key>": {
              "type": "<component type>",
              "props": { ... },
              "children": ["<child key>", ...]
            }
          }
        }

        Rules:
        - Each element must have a unique key
        - The "root" field must reference an existing element key
        - Child keys must reference existing element keys
        - Only components marked "Can contain children: Yes" can have children
        """

        return prompt
    }
}

// MARK: - Core 8 Placeholder Definitions

// Note: Full component definitions are implemented in Task 5.2
// These are placeholder definitions for the core8 catalog

/// Placeholder for Text component (full implementation in Task 5.2)
public struct TextComponentDefinitionPlaceholder: UIComponentDefinition {
    public struct Props: Codable, Sendable {
        public let content: String
        public let style: String?
        public let accessibilityLabel: String?

        public init(content: String, style: String? = nil, accessibilityLabel: String? = nil) {
            self.content = content
            self.style = style
            self.accessibilityLabel = accessibilityLabel
        }
    }

    public static let type = "Text"
    public static let description = "Display text content"
    public static let hasChildren = false
    public static let propsSchemaDescription = "{ content: string, style?: string, accessibilityLabel?: string }"

    public static func validate(props: Props) throws {
        if props.content.isEmpty {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "content",
                reason: "Content cannot be empty"
            )
        }
    }
}

/// Placeholder for Button component (full implementation in Task 5.2)
public struct ButtonComponentDefinitionPlaceholder: UIComponentDefinition {
    public struct Props: Codable, Sendable {
        public let title: String
        public let action: String
        public let style: String?
        public let disabled: Bool?
        public let accessibilityLabel: String?
        public let accessibilityHint: String?
        public let accessibilityTraits: [String]?

        public init(
            title: String,
            action: String,
            style: String? = nil,
            disabled: Bool? = nil,
            accessibilityLabel: String? = nil,
            accessibilityHint: String? = nil,
            accessibilityTraits: [String]? = nil
        ) {
            self.title = title
            self.action = action
            self.style = style
            self.disabled = disabled
            self.accessibilityLabel = accessibilityLabel
            self.accessibilityHint = accessibilityHint
            self.accessibilityTraits = accessibilityTraits
        }
    }

    public static let type = "Button"
    public static let description = "Interactive button that triggers an action"
    public static let hasChildren = false
    public static let propsSchemaDescription = """
        { title: string, action: string, style?: string, disabled?: boolean, \
        accessibilityLabel?: string, accessibilityHint?: string, accessibilityTraits?: string[] }
        """

    public static func validate(props: Props) throws {
        if props.title.isEmpty {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "title",
                reason: "Title cannot be empty"
            )
        }
        if props.action.isEmpty {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "action",
                reason: "Action cannot be empty"
            )
        }
    }
}

/// Placeholder for Card component (full implementation in Task 5.2)
public struct CardComponentDefinitionPlaceholder: UIComponentDefinition {
    public struct Props: Codable, Sendable {
        public let title: String?
        public let subtitle: String?
        public let style: String?

        public init(title: String? = nil, subtitle: String? = nil, style: String? = nil) {
            self.title = title
            self.subtitle = subtitle
            self.style = style
        }
    }

    public static let type = "Card"
    public static let description = "Container card with optional title and subtitle"
    public static let hasChildren = true
    public static let propsSchemaDescription = "{ title?: string, subtitle?: string, style?: string }"
}

/// Placeholder for Input component (full implementation in Task 5.2)
public struct InputComponentDefinitionPlaceholder: UIComponentDefinition {
    public struct Props: Codable, Sendable {
        public let label: String
        public let placeholder: String?
        public let name: String
        public let type: String?
        public let required: Bool?
        public let validation: String?

        public init(
            label: String,
            name: String,
            placeholder: String? = nil,
            type: String? = nil,
            required: Bool? = nil,
            validation: String? = nil
        ) {
            self.label = label
            self.name = name
            self.placeholder = placeholder
            self.type = type
            self.required = required
            self.validation = validation
        }
    }

    public static let type = "Input"
    public static let description = "Text input field for user data entry"
    public static let hasChildren = false
    public static let propsSchemaDescription = """
        { label: string, name: string, placeholder?: string, type?: 'text'|'email'|'password'|'number', \
        required?: boolean, validation?: string }
        """

    public static func validate(props: Props) throws {
        if props.label.isEmpty {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "label",
                reason: "Label cannot be empty"
            )
        }
        if props.name.isEmpty {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "name",
                reason: "Name cannot be empty"
            )
        }
    }
}

/// Placeholder for List component (full implementation in Task 5.2)
public struct ListComponentDefinitionPlaceholder: UIComponentDefinition {
    public struct Props: Codable, Sendable {
        public let style: String?

        public init(style: String? = nil) {
            self.style = style
        }
    }

    public static let type = "List"
    public static let description = "Ordered or unordered list container"
    public static let hasChildren = true
    public static let propsSchemaDescription = "{ style?: 'ordered'|'unordered'|'plain' }"
}

/// Placeholder for Image component (full implementation in Task 5.2)
public struct ImageComponentDefinitionPlaceholder: UIComponentDefinition {
    public struct Props: Codable, Sendable {
        public let url: String
        public let alt: String?
        public let width: Double?
        public let height: Double?

        public init(url: String, alt: String? = nil, width: Double? = nil, height: Double? = nil) {
            self.url = url
            self.alt = alt
            self.width = width
            self.height = height
        }
    }

    public static let type = "Image"
    public static let description = "Display an image from URL"
    public static let hasChildren = false
    public static let propsSchemaDescription = "{ url: string, alt?: string, width?: number, height?: number }"

    public static func validate(props: Props) throws {
        if props.url.isEmpty {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "url",
                reason: "URL cannot be empty"
            )
        }
        if let width = props.width, width <= 0 {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "width",
                reason: "Width must be positive"
            )
        }
        if let height = props.height, height <= 0 {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "height",
                reason: "Height must be positive"
            )
        }
    }
}

/// Placeholder for Stack component (full implementation in Task 5.2)
public struct StackComponentDefinitionPlaceholder: UIComponentDefinition {
    public struct Props: Codable, Sendable {
        public let direction: String
        public let spacing: Double?
        public let alignment: String?

        public init(direction: String = "vertical", spacing: Double? = nil, alignment: String? = nil) {
            self.direction = direction
            self.spacing = spacing
            self.alignment = alignment
        }
    }

    public static let type = "Stack"
    public static let description = "Layout container for horizontal or vertical arrangement"
    public static let hasChildren = true
    public static let propsSchemaDescription = """
        { direction: 'horizontal'|'vertical', spacing?: number, alignment?: 'leading'|'center'|'trailing' }
        """

    public static func validate(props: Props) throws {
        let validDirections = ["horizontal", "vertical"]
        if !validDirections.contains(props.direction) {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "direction",
                reason: "Direction must be 'horizontal' or 'vertical'"
            )
        }
        if let spacing = props.spacing, spacing < 0 {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "spacing",
                reason: "Spacing cannot be negative"
            )
        }
        if let alignment = props.alignment {
            let validAlignments = ["leading", "center", "trailing"]
            if !validAlignments.contains(alignment) {
                throw UIComponentValidationError.invalidPropValue(
                    component: type,
                    prop: "alignment",
                    reason: "Alignment must be 'leading', 'center', or 'trailing'"
                )
            }
        }
    }
}

/// Placeholder for Spacer component (full implementation in Task 5.2)
public struct SpacerComponentDefinitionPlaceholder: UIComponentDefinition {
    public struct Props: Codable, Sendable {
        public let size: Double?

        public init(size: Double? = nil) {
            self.size = size
        }
    }

    public static let type = "Spacer"
    public static let description = "Flexible space between elements"
    public static let hasChildren = false
    public static let propsSchemaDescription = "{ size?: number }"

    public static func validate(props: Props) throws {
        if let size = props.size, size < 0 {
            throw UIComponentValidationError.invalidPropValue(
                component: type,
                prop: "size",
                reason: "Size cannot be negative"
            )
        }
    }
}

// MARK: - Core 8 Catalog

extension UICatalog {
    /// Default catalog with Core 8 components
    ///
    /// The Core 8 components are:
    /// - **Text**: Display text content
    /// - **Button**: Interactive button
    /// - **Card**: Container with title/subtitle
    /// - **Input**: Text input field
    /// - **List**: Ordered/unordered list
    /// - **Image**: Image display
    /// - **Stack**: Layout container (horizontal/vertical)
    /// - **Spacer**: Flexible space
    public static var core8: UICatalog {
        var catalog = UICatalog()

        // Register Core 8 components
        catalog.register(TextComponentDefinitionPlaceholder.self)
        catalog.register(ButtonComponentDefinitionPlaceholder.self)
        catalog.register(CardComponentDefinitionPlaceholder.self)
        catalog.register(InputComponentDefinitionPlaceholder.self)
        catalog.register(ListComponentDefinitionPlaceholder.self)
        catalog.register(ImageComponentDefinitionPlaceholder.self)
        catalog.register(StackComponentDefinitionPlaceholder.self)
        catalog.register(SpacerComponentDefinitionPlaceholder.self)

        // Register common actions
        catalog.registerAction(UIActionDefinition(
            name: "submit",
            description: "Submit a form",
            parametersDescription: "{ formId?: string }"
        ))
        catalog.registerAction(UIActionDefinition(
            name: "navigate",
            description: "Navigate to a destination",
            parametersDescription: "{ destination: string }"
        ))
        catalog.registerAction(UIActionDefinition(
            name: "dismiss",
            description: "Dismiss the current UI"
        ))

        // Register common validators
        catalog.registerValidator(UIValidatorDefinition(
            name: "required",
            description: "Field must have a value"
        ))
        catalog.registerValidator(UIValidatorDefinition(
            name: "email",
            description: "Field must be a valid email address"
        ))
        catalog.registerValidator(UIValidatorDefinition(
            name: "minLength",
            description: "Field must have minimum length",
            parametersDescription: "{ length: number }"
        ))
        catalog.registerValidator(UIValidatorDefinition(
            name: "maxLength",
            description: "Field must not exceed maximum length",
            parametersDescription: "{ length: number }"
        ))
        catalog.registerValidator(UIValidatorDefinition(
            name: "pattern",
            description: "Field must match regex pattern",
            parametersDescription: "{ pattern: string }"
        ))

        return catalog
    }
}
