//
//  UICatalog.swift
//  AISDK
//
//  Component catalog for generative UI with json-render pattern
//  Defines available UI components for LLM prompt generation
//

import Foundation

// MARK: - UIComponentDefinition Protocol

/// Protocol defining a UI component that can be generated by LLM
///
/// Each component definition describes:
/// - The component type name (used in JSON)
/// - Human-readable description for the LLM
/// - Whether it can contain child components
/// - Schema description for the props
/// - Validation logic for incoming props
public protocol UIComponentDefinition: Sendable {
    /// The props type for this component
    associatedtype Props: Codable & Sendable

    /// The type identifier used in JSON (e.g., "Text", "Button")
    static var type: String { get }

    /// Human-readable description for the LLM prompt
    static var description: String { get }

    /// Whether this component can contain children
    static var hasChildren: Bool { get }

    /// Human-readable description of the props schema for LLM
    static var propsSchemaDescription: String { get }

    /// Allowed prop keys for strict validation (empty = allow all)
    static var allowedPropKeys: Set<String> { get }

    /// Validate decoded props, throwing on invalid values
    ///
    /// - Parameter props: The decoded props to validate
    /// - Throws: `UIComponentValidationError` if validation fails
    static func validate(props: Props) throws

    /// Catalog-aware validation for props that reference actions/validators
    ///
    /// - Parameters:
    ///   - props: The decoded props to validate
    ///   - actions: Registered action names in the catalog
    ///   - validators: Registered validator names in the catalog
    /// - Throws: `UIComponentValidationError` if validation fails
    static func validateWithCatalog(
        props: Props,
        actions: Set<String>,
        validators: Set<String>
    ) throws
}

// MARK: - Default Implementation

extension UIComponentDefinition {
    /// Default validation - no-op (override for custom validation)
    public static func validate(props: Props) throws {
        // Default implementation does nothing
    }

    /// Default catalog-aware validation - delegates to regular validation
    public static func validateWithCatalog(
        props: Props,
        actions: Set<String>,
        validators: Set<String>
    ) throws {
        // Default implementation just calls regular validation
        try validate(props: props)
    }

    /// Default allowed prop keys - empty means no strict validation
    public static var allowedPropKeys: Set<String> {
        []
    }
}

// MARK: - UIActionDefinition

/// Definition of an action that can be triggered by UI components
public struct UIActionDefinition: Sendable {
    /// The action identifier
    public let name: String

    /// Human-readable description
    public let description: String

    /// Parameter schema description
    public let parametersDescription: String?

    public init(
        name: String,
        description: String,
        parametersDescription: String? = nil
    ) {
        self.name = name
        self.description = description
        self.parametersDescription = parametersDescription
    }
}

// MARK: - UIValidatorDefinition

/// Definition of a validator that can be used on input components
public struct UIValidatorDefinition: Sendable {
    /// The validator identifier
    public let name: String

    /// Human-readable description
    public let description: String

    /// Parameter schema description
    public let parametersDescription: String?

    public init(
        name: String,
        description: String,
        parametersDescription: String? = nil
    ) {
        self.name = name
        self.description = description
        self.parametersDescription = parametersDescription
    }
}

// MARK: - UIComponentValidationError

/// Errors that can occur during component validation
public enum UIComponentValidationError: Error, Sendable {
    /// A required prop is missing during decoding
    case missingRequiredProp(component: String, prop: String)

    /// A prop value is invalid
    case invalidPropValue(component: String, prop: String, reason: String)

    /// Component type is not registered
    case unknownComponentType(String)

    /// General validation failure (includes decoding failures)
    case validationFailed(component: String, reason: String)

    /// Props data failed to decode
    case decodingFailed(component: String, reason: String)

    /// Unknown prop key in JSON (strict mode)
    case unknownProp(component: String, prop: String)

    /// Action name not registered in catalog
    case unknownAction(component: String, action: String)

    /// Validator name not registered in catalog
    case unknownValidator(component: String, validator: String)

    /// Component type name is invalid (empty or whitespace)
    case invalidComponentTypeName(String)

    /// Duplicate component type registration attempted
    case duplicateComponentType(String)
}

extension UIComponentValidationError: LocalizedError {
    public var errorDescription: String? {
        switch self {
        case .missingRequiredProp(let component, let prop):
            return "Component '\(component)' missing required prop '\(prop)'"
        case .invalidPropValue(let component, let prop, let reason):
            return "Component '\(component)' has invalid value for prop '\(prop)': \(reason)"
        case .unknownComponentType(let type):
            return "Unknown component type: \(type)"
        case .validationFailed(let component, let reason):
            return "Component '\(component)' validation failed: \(reason)"
        case .decodingFailed(let component, let reason):
            return "Component '\(component)' props decoding failed: \(reason)"
        case .unknownProp(let component, let prop):
            return "Component '\(component)' has unknown prop '\(prop)'"
        case .unknownAction(let component, let action):
            return "Component '\(component)' references unknown action '\(action)'"
        case .unknownValidator(let component, let validator):
            return "Component '\(component)' references unknown validator '\(validator)'"
        case .invalidComponentTypeName(let name):
            return "Invalid component type name: '\(name)' (must be non-empty)"
        case .duplicateComponentType(let type):
            return "Duplicate component type registration: '\(type)'"
        }
    }
}

// MARK: - AnyUIComponentDefinition

/// Type-erased wrapper for UIComponentDefinition
///
/// Enables storing heterogeneous component definitions in collections.
public struct AnyUIComponentDefinition: Sendable {
    /// The component type identifier
    public let type: String

    /// Human-readable description
    public let description: String

    /// Whether this component supports children
    public let hasChildren: Bool

    /// Props schema description for LLM
    public let propsSchemaDescription: String

    /// Allowed prop keys for strict validation
    public let allowedPropKeys: Set<String>

    /// Type-erased validation function that always throws UIComponentValidationError
    private let _validateWithCatalog: @Sendable (Data, Set<String>, Set<String>) throws -> Void

    /// Creates a type-erased wrapper for a component definition
    ///
    /// - Parameter definitionType: The concrete UIComponentDefinition type
    public init<T: UIComponentDefinition>(_ definitionType: T.Type) {
        self.type = T.type
        self.description = T.description
        self.hasChildren = T.hasChildren
        self.propsSchemaDescription = T.propsSchemaDescription
        self.allowedPropKeys = T.allowedPropKeys

        let componentType = T.type  // Capture for closure
        let allowedKeys = T.allowedPropKeys

        self._validateWithCatalog = { data, actions, validators in
            // First, check for unknown keys if strict validation is enabled
            if !allowedKeys.isEmpty {
                try Self.validateUnknownKeys(
                    data: data,
                    allowedKeys: allowedKeys,
                    componentType: componentType
                )
            }

            // Decode props with error wrapping
            let decoder = JSONDecoder()
            decoder.keyDecodingStrategy = .convertFromSnakeCase

            let props: T.Props
            do {
                props = try decoder.decode(T.Props.self, from: data)
            } catch let decodingError as DecodingError {
                // Extract meaningful error message from DecodingError
                let reason: String
                switch decodingError {
                case .keyNotFound(let key, _):
                    throw UIComponentValidationError.missingRequiredProp(
                        component: componentType,
                        prop: key.stringValue
                    )
                case .typeMismatch(let expectedType, let context):
                    reason = "Expected \(expectedType) at \(context.codingPath.map(\.stringValue).joined(separator: "."))"
                case .valueNotFound(let expectedType, let context):
                    reason = "Missing value of type \(expectedType) at \(context.codingPath.map(\.stringValue).joined(separator: "."))"
                case .dataCorrupted(let context):
                    reason = context.debugDescription
                @unknown default:
                    reason = decodingError.localizedDescription
                }
                throw UIComponentValidationError.decodingFailed(
                    component: componentType,
                    reason: reason
                )
            } catch {
                throw UIComponentValidationError.decodingFailed(
                    component: componentType,
                    reason: error.localizedDescription
                )
            }

            // Run catalog-aware validation
            do {
                try T.validateWithCatalog(props: props, actions: actions, validators: validators)
            } catch let validationError as UIComponentValidationError {
                throw validationError
            } catch {
                throw UIComponentValidationError.validationFailed(
                    component: componentType,
                    reason: error.localizedDescription
                )
            }
        }
    }

    /// Check for unknown keys in JSON data
    private static func validateUnknownKeys(
        data: Data,
        allowedKeys: Set<String>,
        componentType: String
    ) throws {
        // Parse JSON to get all keys
        guard let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return  // Let decoder handle malformed JSON
        }

        // Convert snake_case keys to camelCase for comparison
        let jsonKeys = Set(json.keys.map { key -> String in
            // Convert snake_case to camelCase
            let parts = key.split(separator: "_")
            if parts.count <= 1 { return key }
            return parts.enumerated().map { index, part in
                index == 0 ? String(part) : String(part).capitalized
            }.joined()
        })

        // Find unknown keys
        for key in jsonKeys {
            if !allowedKeys.contains(key) {
                throw UIComponentValidationError.unknownProp(
                    component: componentType,
                    prop: key
                )
            }
        }
    }

    /// Validate props data for this component (without catalog context)
    ///
    /// - Parameter propsData: JSON data for the props
    /// - Throws: `UIComponentValidationError` for any validation or decoding failure
    public func validate(propsData: Data) throws {
        // Validate without catalog context (empty action/validator sets)
        try _validateWithCatalog(propsData, [], [])
    }

    /// Validate props data with catalog context for action/validator validation
    ///
    /// - Parameters:
    ///   - propsData: JSON data for the props
    ///   - actions: Registered action names in the catalog
    ///   - validators: Registered validator names in the catalog
    /// - Throws: `UIComponentValidationError` for any validation or decoding failure
    public func validateWithCatalog(
        propsData: Data,
        actions: Set<String>,
        validators: Set<String>
    ) throws {
        try _validateWithCatalog(propsData, actions, validators)
    }
}

// MARK: - UICatalog

/// Component catalog defining available UI components for LLM
///
/// `UICatalog` is the central registry for generative UI components. It provides:
/// - Component definitions with props schemas
/// - Action definitions for interactive elements
/// - Validator definitions for input validation
/// - System prompt generation for LLM context
///
/// ## Usage
/// ```swift
/// // Use the default Core 8 catalog
/// let catalog = UICatalog.core8
///
/// // Generate system prompt for LLM
/// let prompt = catalog.generatePrompt()
/// ```
///
/// ## Custom Catalog
/// ```swift
/// var catalog = UICatalog()
/// catalog.register(MyCustomComponent.self)
/// catalog.registerAction(UIActionDefinition(name: "submit", description: "Submit form"))
/// ```
public struct UICatalog: Sendable {
    /// Registered component definitions by type name
    public private(set) var components: [String: AnyUIComponentDefinition]

    /// Registered action definitions by name
    public private(set) var actions: [String: UIActionDefinition]

    /// Registered validator definitions by name
    public private(set) var validators: [String: UIValidatorDefinition]

    /// Creates an empty catalog
    public init() {
        self.components = [:]
        self.actions = [:]
        self.validators = [:]
    }

    /// Creates a catalog with predefined components (internal, unchecked)
    ///
    /// - Parameter componentTypes: Array of component definition types to register
    /// - Note: Uses unchecked registration - assumes valid, non-duplicate types.
    ///         For public use, create an empty catalog and use `register` method.
    init<each T: UIComponentDefinition>(componentTypes: repeat (each T).Type) {
        self.components = [:]
        self.actions = [:]
        self.validators = [:]
        repeat registerUnchecked((each componentTypes))
    }

    // MARK: - Registration

    /// Register a component definition
    ///
    /// - Parameter definitionType: The component definition type to register
    /// - Throws: `UIComponentValidationError.invalidComponentTypeName` if type name is empty/whitespace,
    ///           `UIComponentValidationError.duplicateComponentType` if type is already registered
    public mutating func register<T: UIComponentDefinition>(_ definitionType: T.Type) throws {
        let typeName = T.type.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !typeName.isEmpty else {
            throw UIComponentValidationError.invalidComponentTypeName(T.type)
        }
        // Reject types with leading/trailing whitespace to ensure consistency
        guard T.type == typeName else {
            throw UIComponentValidationError.invalidComponentTypeName(T.type)
        }
        guard components[typeName] == nil else {
            throw UIComponentValidationError.duplicateComponentType(typeName)
        }
        let wrapped = AnyUIComponentDefinition(definitionType)
        components[typeName] = wrapped
    }

    /// Register a component definition (internal, non-throwing for core8 initialization)
    ///
    /// - Parameter definitionType: The component definition type to register
    /// - Note: This method is internal and used for core8 catalog initialization
    mutating func registerUnchecked<T: UIComponentDefinition>(_ definitionType: T.Type) {
        let wrapped = AnyUIComponentDefinition(definitionType)
        components[T.type] = wrapped
    }

    /// Register an action definition
    ///
    /// - Parameter action: The action definition to register
    public mutating func registerAction(_ action: UIActionDefinition) {
        actions[action.name] = action
    }

    /// Register a validator definition
    ///
    /// - Parameter validator: The validator definition to register
    public mutating func registerValidator(_ validator: UIValidatorDefinition) {
        validators[validator.name] = validator
    }

    // MARK: - Lookup

    /// Get a component definition by type name
    ///
    /// - Parameter type: The component type identifier
    /// - Returns: The component definition, or nil if not found
    public func component(forType type: String) -> AnyUIComponentDefinition? {
        components[type]
    }

    /// Check if a component type is registered
    ///
    /// - Parameter type: The component type identifier
    /// - Returns: True if the component is registered
    public func hasComponent(_ type: String) -> Bool {
        components[type] != nil
    }

    /// Get all registered component type names (sorted)
    public var registeredComponentTypes: [String] {
        components.keys.sorted()
    }

    // MARK: - Validation

    /// Validate a component type and its props
    ///
    /// - Parameters:
    ///   - type: The component type identifier
    ///   - propsData: JSON data for the props
    /// - Throws: `UIComponentValidationError` if validation fails (including decoding errors,
    ///           unknown props, unknown actions/validators)
    public func validate(type: String, propsData: Data) throws {
        guard let definition = components[type] else {
            throw UIComponentValidationError.unknownComponentType(type)
        }
        // Use catalog-aware validation to check action/validator references
        try definition.validateWithCatalog(
            propsData: propsData,
            actions: Set(actions.keys),
            validators: Set(validators.keys)
        )
    }

    // MARK: - Prompt Generation

    /// Generate a system prompt describing available components for LLM
    ///
    /// This prompt can be included in the system message to inform the LLM
    /// about available UI components and the expected output format.
    ///
    /// - Returns: A formatted prompt string
    public func generatePrompt() -> String {
        var prompt = "You can generate UI using these components:\n\n"

        // Sort by type name for deterministic output
        let sortedComponents = components.sorted { $0.key < $1.key }

        for (_, definition) in sortedComponents {
            prompt += "## \(definition.type)\n"
            prompt += "Description: \(definition.description)\n"
            prompt += "Props: \(definition.propsSchemaDescription)\n"
            if definition.hasChildren {
                prompt += "Can contain children: Yes\n"
            } else {
                prompt += "Can contain children: No\n"
            }
            prompt += "\n"
        }

        // Add actions section if any registered
        if !actions.isEmpty {
            prompt += "## Available Actions\n\n"
            let sortedActions = actions.sorted { $0.key < $1.key }
            for (_, action) in sortedActions {
                prompt += "- **\(action.name)**: \(action.description)"
                if let params = action.parametersDescription {
                    prompt += " (Parameters: \(params))"
                }
                prompt += "\n"
            }
            prompt += "\n"
        }

        // Add validators section if any registered
        if !validators.isEmpty {
            prompt += "## Available Validators\n\n"
            let sortedValidators = validators.sorted { $0.key < $1.key }
            for (_, validator) in sortedValidators {
                prompt += "- **\(validator.name)**: \(validator.description)"
                if let params = validator.parametersDescription {
                    prompt += " (Parameters: \(params))"
                }
                prompt += "\n"
            }
            prompt += "\n"
        }

        // Add output format specification (json-render pattern)
        prompt += """

        Output format: JSON with structure:
        {
          "root": "<key of root element>",
          "elements": {
            "<key>": {
              "type": "<component type>",
              "props": { ... },
              "children": ["<child key>", ...]
            }
          }
        }

        Rules:
        - Each element must have a unique key
        - The "root" field must reference an existing element key
        - Child keys must reference existing element keys
        - Only components marked "Can contain children: Yes" may have a "children" array
        - Components marked "Can contain children: No" must omit the "children" field
        - Use only registered component types listed above
        """

        return prompt
    }
}

// MARK: - Supporting Types for Core 8 Components

/// Input type enum for validation
public enum InputType: String, Codable, Sendable {
    case text
    case email
    case password
    case number
}

/// List style enum for validation (prefixed to avoid SwiftUI naming conflict)
public enum UIListStyle: String, Codable, Sendable {
    case ordered
    case unordered
    case plain
}

/// Stack direction enum for validation
public enum StackDirection: String, Codable, Sendable {
    case horizontal
    case vertical
}

/// Stack alignment enum for validation
public enum StackAlignment: String, Codable, Sendable {
    case leading
    case center
    case trailing
}

// MARK: - Core 8 Catalog

extension UICatalog {
    /// Default catalog with Core 8 components
    ///
    /// The Core 8 components are:
    /// - **Text**: Display text content
    /// - **Button**: Interactive button
    /// - **Card**: Container with title/subtitle
    /// - **Input**: Text input field
    /// - **List**: Ordered/unordered list
    /// - **Image**: Image display
    /// - **Stack**: Layout container (horizontal/vertical)
    /// - **Spacer**: Flexible space
    public static let core8: UICatalog = {
        var catalog = UICatalog()

        // Register Core 8 components (public definitions from Core8Components.swift)
        catalog.registerUnchecked(TextComponentDefinition.self)
        catalog.registerUnchecked(ButtonComponentDefinition.self)
        catalog.registerUnchecked(CardComponentDefinition.self)
        catalog.registerUnchecked(InputComponentDefinition.self)
        catalog.registerUnchecked(ListComponentDefinition.self)
        catalog.registerUnchecked(ImageComponentDefinition.self)
        catalog.registerUnchecked(StackComponentDefinition.self)
        catalog.registerUnchecked(SpacerComponentDefinition.self)

        // Register common actions
        catalog.registerAction(UIActionDefinition(
            name: "submit",
            description: "Submit a form",
            parametersDescription: "{ formId?: string }"
        ))
        catalog.registerAction(UIActionDefinition(
            name: "navigate",
            description: "Navigate to a destination",
            parametersDescription: "{ destination: string }"
        ))
        catalog.registerAction(UIActionDefinition(
            name: "dismiss",
            description: "Dismiss the current UI"
        ))

        // Register common validators
        catalog.registerValidator(UIValidatorDefinition(
            name: "required",
            description: "Field must have a value"
        ))
        catalog.registerValidator(UIValidatorDefinition(
            name: "email",
            description: "Field must be a valid email address"
        ))
        catalog.registerValidator(UIValidatorDefinition(
            name: "minLength",
            description: "Field must have minimum length",
            parametersDescription: "{ length: number }"
        ))
        catalog.registerValidator(UIValidatorDefinition(
            name: "maxLength",
            description: "Field must not exceed maximum length",
            parametersDescription: "{ length: number }"
        ))
        catalog.registerValidator(UIValidatorDefinition(
            name: "pattern",
            description: "Field must match regex pattern",
            parametersDescription: "{ pattern: string }"
        ))

        return catalog
    }()
}

// MARK: - Extended Catalogs

extension UICatalog {
    /// Extended catalog with Tier 1, Charts, Interactive, and Layout components
    public static let extended: UICatalog = {
        var catalog = core8
        catalog.registerUnchecked(MetricComponentDefinition.self)
        catalog.registerUnchecked(BadgeComponentDefinition.self)
        catalog.registerUnchecked(DividerComponentDefinition.self)
        catalog.registerUnchecked(SectionComponentDefinition.self)
        catalog.registerUnchecked(ProgressComponentDefinition.self)
        catalog.registerUnchecked(BarChartComponentDefinition.self)
        catalog.registerUnchecked(LineChartComponentDefinition.self)
        catalog.registerUnchecked(PieChartComponentDefinition.self)
        catalog.registerUnchecked(GaugeComponentDefinition.self)
        catalog.registerUnchecked(ToggleComponentDefinition.self)
        catalog.registerUnchecked(SliderComponentDefinition.self)
        catalog.registerUnchecked(StepperComponentDefinition.self)
        catalog.registerUnchecked(SegmentedControlComponentDefinition.self)
        catalog.registerUnchecked(PickerComponentDefinition.self)
        catalog.registerUnchecked(GridComponentDefinition.self)
        catalog.registerUnchecked(TabsComponentDefinition.self)
        catalog.registerUnchecked(AccordionComponentDefinition.self)
        return catalog
    }()

    /// Dashboard-focused catalog (Core 8 + Tier 1 + Charts)
    public static let dashboard: UICatalog = {
        var catalog = core8
        catalog.registerUnchecked(MetricComponentDefinition.self)
        catalog.registerUnchecked(BadgeComponentDefinition.self)
        catalog.registerUnchecked(DividerComponentDefinition.self)
        catalog.registerUnchecked(SectionComponentDefinition.self)
        catalog.registerUnchecked(ProgressComponentDefinition.self)
        catalog.registerUnchecked(BarChartComponentDefinition.self)
        catalog.registerUnchecked(LineChartComponentDefinition.self)
        catalog.registerUnchecked(PieChartComponentDefinition.self)
        catalog.registerUnchecked(GaugeComponentDefinition.self)
        return catalog
    }()
}
